export interface HizbInfo {
  number: number;
  juzNumber: number;
  nameArabic: string;
  nameEnglish: string;
  startSurahNumber: number;
  startSurahName: string;
  startAyahNumber: number;
  endSurahNumber: number;
  endSurahName: string;
  endAyahNumber: number;
  description: string;
}

export const HIZB_LIST: HizbInfo[] = [
  { number: 1, juzNumber: 1, nameArabic: "الحزب ١", nameEnglish: "Hizb 1", startSurahNumber: 1, startSurahName: "Al-Fatihah", startAyahNumber: 1, endSurahNumber: 2, endSurahName: "Al-Baqarah", endAyahNumber: 74, description: "Al-Fatihah 1 - Al-Baqarah 74" },
  { number: 2, juzNumber: 1, nameArabic: "الحزب ٢", nameEnglish: "Hizb 2", startSurahNumber: 2, startSurahName: "Al-Baqarah", startAyahNumber: 75, endSurahNumber: 2, endSurahName: "Al-Baqarah", endAyahNumber: 141, description: "Al-Baqarah 75 - Al-Baqarah 141" },
  { number: 3, juzNumber: 2, nameArabic: "الحزب ٣", nameEnglish: "Hizb 3", startSurahNumber: 2, startSurahName: "Al-Baqarah", startAyahNumber: 142, endSurahNumber: 2, endSurahName: "Al-Baqarah", endAyahNumber: 202, description: "Al-Baqarah 142 - Al-Baqarah 202" },
  { number: 4, juzNumber: 2, nameArabic: "الحزب ٤", nameEnglish: "Hizb 4", startSurahNumber: 2, startSurahName: "Al-Baqarah", startAyahNumber: 203, endSurahNumber: 2, endSurahName: "Al-Baqarah", endAyahNumber: 252, description: "Al-Baqarah 203 - Al-Baqarah 252" },
  { number: 5, juzNumber: 3, nameArabic: "الحزب ٥", nameEnglish: "Hizb 5", startSurahNumber: 2, startSurahName: "Al-Baqarah", startAyahNumber: 253, endSurahNumber: 3, endSurahName: "Ali 'Imran", endAyahNumber: 14, description: "Al-Baqarah 253 - Ali 'Imran 14" },
  { number: 6, juzNumber: 3, nameArabic: "الحزب ٦", nameEnglish: "Hizb 6", startSurahNumber: 3, startSurahName: "Ali 'Imran", startAyahNumber: 15, endSurahNumber: 3, endSurahName: "Ali 'Imran", endAyahNumber: 92, description: "Ali 'Imran 15 - Ali 'Imran 92" },
  { number: 7, juzNumber: 4, nameArabic: "الحزب ٧", nameEnglish: "Hizb 7", startSurahNumber: 3, startSurahName: "Ali 'Imran", startAyahNumber: 93, endSurahNumber: 3, endSurahName: "Ali 'Imran", endAyahNumber: 170, description: "Ali 'Imran 93 - Ali 'Imran 170" },
  { number: 8, juzNumber: 4, nameArabic: "الحزب ٨", nameEnglish: "Hizb 8", startSurahNumber: 3, startSurahName: "Ali 'Imran", startAyahNumber: 171, endSurahNumber: 4, endSurahName: "An-Nisa", endAyahNumber: 23, description: "Ali 'Imran 171 - An-Nisa 23" },
  { number: 9, juzNumber: 5, nameArabic: "الحزب ٩", nameEnglish: "Hizb 9", startSurahNumber: 4, startSurahName: "An-Nisa", startAyahNumber: 24, endSurahNumber: 4, endSurahName: "An-Nisa", endAyahNumber: 87, description: "An-Nisa 24 - An-Nisa 87" },
  { number: 10, juzNumber: 5, nameArabic: "الحزب ١٠", nameEnglish: "Hizb 10", startSurahNumber: 4, startSurahName: "An-Nisa", startAyahNumber: 88, endSurahNumber: 4, endSurahName: "An-Nisa", endAyahNumber: 147, description: "An-Nisa 88 - An-Nisa 147" },
  { number: 11, juzNumber: 6, nameArabic: "الحزب ١١", nameEnglish: "Hizb 11", startSurahNumber: 4, startSurahName: "An-Nisa", startAyahNumber: 148, endSurahNumber: 5, endSurahName: "Al-Ma'idah", endAyahNumber: 26, description: "An-Nisa 148 - Al-Ma'idah 26" },
  { number: 12, juzNumber: 6, nameArabic: "الحزب ١٢", nameEnglish: "Hizb 12", startSurahNumber: 5, startSurahName: "Al-Ma'idah", startAyahNumber: 27, endSurahNumber: 5, endSurahName: "Al-Ma'idah", endAyahNumber: 81, description: "Al-Ma'idah 27 - Al-Ma'idah 81" },
  { number: 13, juzNumber: 7, nameArabic: "الحزب ١٣", nameEnglish: "Hizb 13", startSurahNumber: 5, startSurahName: "Al-Ma'idah", startAyahNumber: 82, endSurahNumber: 6, endSurahName: "Al-An'am", endAyahNumber: 35, description: "Al-Ma'idah 82 - Al-An'am 35" },
  { number: 14, juzNumber: 7, nameArabic: "الحزب ١٤", nameEnglish: "Hizb 14", startSurahNumber: 6, startSurahName: "Al-An'am", startAyahNumber: 36, endSurahNumber: 6, endSurahName: "Al-An'am", endAyahNumber: 110, description: "Al-An'am 36 - Al-An'am 110" },
  { number: 15, juzNumber: 8, nameArabic: "الحزب ١٥", nameEnglish: "Hizb 15", startSurahNumber: 6, startSurahName: "Al-An'am", startAyahNumber: 111, endSurahNumber: 6, endSurahName: "Al-An'am", endAyahNumber: 165, description: "Al-An'am 111 - Al-An'am 165" },
  { number: 16, juzNumber: 8, nameArabic: "الحزب ١٦", nameEnglish: "Hizb 16", startSurahNumber: 7, startSurahName: "Al-A'raf", startAyahNumber: 1, endSurahNumber: 7, endSurahName: "Al-A'raf", endAyahNumber: 87, description: "Al-A'raf 1 - Al-A'raf 87" },
  { number: 17, juzNumber: 9, nameArabic: "الحزب ١٧", nameEnglish: "Hizb 17", startSurahNumber: 7, startSurahName: "Al-A'raf", startAyahNumber: 88, endSurahNumber: 7, endSurahName: "Al-A'raf", endAyahNumber: 170, description: "Al-A'raf 88 - Al-A'raf 170" },
  { number: 18, juzNumber: 9, nameArabic: "الحزب ١٨", nameEnglish: "Hizb 18", startSurahNumber: 7, startSurahName: "Al-A'raf", startAyahNumber: 171, endSurahNumber: 8, endSurahName: "Al-Anfal", endAyahNumber: 40, description: "Al-A'raf 171 - Al-Anfal 40" },
  { number: 19, juzNumber: 10, nameArabic: "الحزب ١٩", nameEnglish: "Hizb 19", startSurahNumber: 8, startSurahName: "Al-Anfal", startAyahNumber: 41, endSurahNumber: 9, endSurahName: "At-Tawbah", endAyahNumber: 33, description: "Al-Anfal 41 - At-Tawbah 33" },
  { number: 20, juzNumber: 10, nameArabic: "الحزب ٢٠", nameEnglish: "Hizb 20", startSurahNumber: 9, startSurahName: "At-Tawbah", startAyahNumber: 34, endSurahNumber: 9, endSurahName: "At-Tawbah", endAyahNumber: 92, description: "At-Tawbah 34 - At-Tawbah 92" },
  { number: 21, juzNumber: 11, nameArabic: "الحزب ٢١", nameEnglish: "Hizb 21", startSurahNumber: 9, startSurahName: "At-Tawbah", startAyahNumber: 93, endSurahNumber: 10, endSurahName: "Yunus", endAyahNumber: 25, description: "At-Tawbah 93 - Yunus 25" },
  { number: 22, juzNumber: 11, nameArabic: "الحزب ٢٢", nameEnglish: "Hizb 22", startSurahNumber: 10, startSurahName: "Yunus", startAyahNumber: 26, endSurahNumber: 11, endSurahName: "Hud", endAyahNumber: 5, description: "Yunus 26 - Hud 5" },
  { number: 23, juzNumber: 12, nameArabic: "الحزب ٢٣", nameEnglish: "Hizb 23", startSurahNumber: 11, startSurahName: "Hud", startAyahNumber: 6, endSurahNumber: 11, endSurahName: "Hud", endAyahNumber: 83, description: "Hud 6 - Hud 83" },
  { number: 24, juzNumber: 12, nameArabic: "الحزب ٢٤", nameEnglish: "Hizb 24", startSurahNumber: 11, startSurahName: "Hud", startAyahNumber: 84, endSurahNumber: 12, endSurahName: "Yusuf", endAyahNumber: 52, description: "Hud 84 - Yusuf 52" },
  { number: 25, juzNumber: 13, nameArabic: "الحزب ٢٥", nameEnglish: "Hizb 25", startSurahNumber: 12, startSurahName: "Yusuf", startAyahNumber: 53, endSurahNumber: 13, endSurahName: "Ar-Ra'd", endAyahNumber: 18, description: "Yusuf 53 - Ar-Ra'd 18" },
  { number: 26, juzNumber: 13, nameArabic: "الحزب ٢٦", nameEnglish: "Hizb 26", startSurahNumber: 13, startSurahName: "Ar-Ra'd", startAyahNumber: 19, endSurahNumber: 14, endSurahName: "Ibrahim", endAyahNumber: 52, description: "Ar-Ra'd 19 - Ibrahim 52" },
  { number: 27, juzNumber: 14, nameArabic: "الحزب ٢٧", nameEnglish: "Hizb 27", startSurahNumber: 15, startSurahName: "Al-Hijr", startAyahNumber: 1, endSurahNumber: 16, endSurahName: "An-Nahl", endAyahNumber: 50, description: "Al-Hijr 1 - An-Nahl 50" },
  { number: 28, juzNumber: 14, nameArabic: "الحزب ٢٨", nameEnglish: "Hizb 28", startSurahNumber: 16, startSurahName: "An-Nahl", startAyahNumber: 51, endSurahNumber: 16, endSurahName: "An-Nahl", endAyahNumber: 128, description: "An-Nahl 51 - An-Nahl 128" },
  { number: 29, juzNumber: 15, nameArabic: "الحزب ٢٩", nameEnglish: "Hizb 29", startSurahNumber: 17, startSurahName: "Al-Isra", startAyahNumber: 1, endSurahNumber: 17, endSurahName: "Al-Isra", endAyahNumber: 98, description: "Al-Isra 1 - Al-Isra 98" },
  { number: 30, juzNumber: 15, nameArabic: "الحزب ٣٠", nameEnglish: "Hizb 30", startSurahNumber: 17, startSurahName: "Al-Isra", startAyahNumber: 99, endSurahNumber: 18, endSurahName: "Al-Kahf", endAyahNumber: 74, description: "Al-Isra 99 - Al-Kahf 74" },
  { number: 31, juzNumber: 16, nameArabic: "الحزب ٣١", nameEnglish: "Hizb 31", startSurahNumber: 18, startSurahName: "Al-Kahf", startAyahNumber: 75, endSurahNumber: 19, endSurahName: "Maryam", endAyahNumber: 98, description: "Al-Kahf 75 - Maryam 98" },
  { number: 32, juzNumber: 16, nameArabic: "الحزب ٣٢", nameEnglish: "Hizb 32", startSurahNumber: 20, startSurahName: "Ta-Ha", startAyahNumber: 1, endSurahNumber: 20, endSurahName: "Ta-Ha", endAyahNumber: 135, description: "Ta-Ha 1 - Ta-Ha 135" },
  { number: 33, juzNumber: 17, nameArabic: "الحزب ٣٣", nameEnglish: "Hizb 33", startSurahNumber: 21, startSurahName: "Al-Anbiya", startAyahNumber: 1, endSurahNumber: 21, endSurahName: "Al-Anbiya", endAyahNumber: 112, description: "Al-Anbiya 1 - Al-Anbiya 112" },
  { number: 34, juzNumber: 17, nameArabic: "الحزب ٣٤", nameEnglish: "Hizb 34", startSurahNumber: 22, startSurahName: "Al-Hajj", startAyahNumber: 1, endSurahNumber: 22, endSurahName: "Al-Hajj", endAyahNumber: 78, description: "Al-Hajj 1 - Al-Hajj 78" },
  { number: 35, juzNumber: 18, nameArabic: "الحزب ٣٥", nameEnglish: "Hizb 35", startSurahNumber: 23, startSurahName: "Al-Mu'minun", startAyahNumber: 1, endSurahNumber: 24, endSurahName: "An-Nur", endAyahNumber: 20, description: "Al-Mu'minun 1 - An-Nur 20" },
  { number: 36, juzNumber: 18, nameArabic: "الحزب ٣٦", nameEnglish: "Hizb 36", startSurahNumber: 24, startSurahName: "An-Nur", startAyahNumber: 21, endSurahNumber: 25, endSurahName: "Al-Furqan", endAyahNumber: 20, description: "An-Nur 21 - Al-Furqan 20" },
  { number: 37, juzNumber: 19, nameArabic: "الحزب ٣٧", nameEnglish: "Hizb 37", startSurahNumber: 25, startSurahName: "Al-Furqan", startAyahNumber: 21, endSurahNumber: 26, endSurahName: "Ash-Shu'ara", endAyahNumber: 110, description: "Al-Furqan 21 - Ash-Shu'ara 110" },
  { number: 38, juzNumber: 19, nameArabic: "الحزب ٣٨", nameEnglish: "Hizb 38", startSurahNumber: 26, startSurahName: "Ash-Shu'ara", startAyahNumber: 111, endSurahNumber: 27, endSurahName: "An-Naml", endAyahNumber: 55, description: "Ash-Shu'ara 111 - An-Naml 55" },
  { number: 39, juzNumber: 20, nameArabic: "الحزب ٣٩", nameEnglish: "Hizb 39", startSurahNumber: 27, startSurahName: "An-Naml", startAyahNumber: 56, endSurahNumber: 28, endSurahName: "Al-Qasas", endAyahNumber: 50, description: "An-Naml 56 - Al-Qasas 50" },
  { number: 40, juzNumber: 20, nameArabic: "الحزب ٤٠", nameEnglish: "Hizb 40", startSurahNumber: 28, startSurahName: "Al-Qasas", startAyahNumber: 51, endSurahNumber: 29, endSurahName: "Al-'Ankabut", endAyahNumber: 45, description: "Al-Qasas 51 - Al-'Ankabut 45" },
  { number: 41, juzNumber: 21, nameArabic: "الحزب ٤١", nameEnglish: "Hizb 41", startSurahNumber: 29, startSurahName: "Al-'Ankabut", startAyahNumber: 46, endSurahNumber: 31, endSurahName: "Luqman", endAyahNumber: 21, description: "Al-'Ankabut 46 - Luqman 21" },
  { number: 42, juzNumber: 21, nameArabic: "الحزب ٤٢", nameEnglish: "Hizb 42", startSurahNumber: 31, startSurahName: "Luqman", startAyahNumber: 22, endSurahNumber: 33, endSurahName: "Al-Ahzab", endAyahNumber: 30, description: "Luqman 22 - Al-Ahzab 30" },
  { number: 43, juzNumber: 22, nameArabic: "الحزب ٤٣", nameEnglish: "Hizb 43", startSurahNumber: 33, startSurahName: "Al-Ahzab", startAyahNumber: 31, endSurahNumber: 34, endSurahName: "Saba", endAyahNumber: 23, description: "Al-Ahzab 31 - Saba 23" },
  { number: 44, juzNumber: 22, nameArabic: "الحزب ٤٤", nameEnglish: "Hizb 44", startSurahNumber: 34, startSurahName: "Saba", startAyahNumber: 24, endSurahNumber: 36, endSurahName: "Ya-Sin", endAyahNumber: 27, description: "Saba 24 - Ya-Sin 27" },
  { number: 45, juzNumber: 23, nameArabic: "الحزب ٤٥", nameEnglish: "Hizb 45", startSurahNumber: 36, startSurahName: "Ya-Sin", startAyahNumber: 28, endSurahNumber: 37, endSurahName: "As-Saffat", endAyahNumber: 144, description: "Ya-Sin 28 - As-Saffat 144" },
  { number: 46, juzNumber: 23, nameArabic: "الحزب ٤٦", nameEnglish: "Hizb 46", startSurahNumber: 37, startSurahName: "As-Saffat", startAyahNumber: 145, endSurahNumber: 39, endSurahName: "Az-Zumar", endAyahNumber: 31, description: "As-Saffat 145 - Az-Zumar 31" },
  { number: 47, juzNumber: 24, nameArabic: "الحزب ٤٧", nameEnglish: "Hizb 47", startSurahNumber: 39, startSurahName: "Az-Zumar", startAyahNumber: 32, endSurahNumber: 40, endSurahName: "Ghafir", endAyahNumber: 40, description: "Az-Zumar 32 - Ghafir 40" },
  { number: 48, juzNumber: 24, nameArabic: "الحزب ٤٨", nameEnglish: "Hizb 48", startSurahNumber: 40, startSurahName: "Ghafir", startAyahNumber: 41, endSurahNumber: 41, endSurahName: "Fussilat", endAyahNumber: 46, description: "Ghafir 41 - Fussilat 46" },
  { number: 49, juzNumber: 25, nameArabic: "الحزب ٤٩", nameEnglish: "Hizb 49", startSurahNumber: 41, startSurahName: "Fussilat", startAyahNumber: 47, endSurahNumber: 43, endSurahName: "Az-Zukhruf", endAyahNumber: 23, description: "Fussilat 47 - Az-Zukhruf 23" },
  { number: 50, juzNumber: 25, nameArabic: "الحزب ٥٠", nameEnglish: "Hizb 50", startSurahNumber: 43, startSurahName: "Az-Zukhruf", startAyahNumber: 24, endSurahNumber: 45, endSurahName: "Al-Jathiyah", endAyahNumber: 37, description: "Az-Zukhruf 24 - Al-Jathiyah 37" },
  { number: 51, juzNumber: 26, nameArabic: "الحزب ٥١", nameEnglish: "Hizb 51", startSurahNumber: 46, startSurahName: "Al-Ahqaf", startAyahNumber: 1, endSurahNumber: 48, endSurahName: "Al-Fath", endAyahNumber: 17, description: "Al-Ahqaf 1 - Al-Fath 17" },
  { number: 52, juzNumber: 26, nameArabic: "الحزب ٥٢", nameEnglish: "Hizb 52", startSurahNumber: 48, startSurahName: "Al-Fath", startAyahNumber: 18, endSurahNumber: 51, endSurahName: "Adh-Dhariyat", endAyahNumber: 30, description: "Al-Fath 18 - Adh-Dhariyat 30" },
  { number: 53, juzNumber: 27, nameArabic: "الحزب ٥٣", nameEnglish: "Hizb 53", startSurahNumber: 51, startSurahName: "Adh-Dhariyat", startAyahNumber: 31, endSurahNumber: 54, endSurahName: "Al-Qamar", endAyahNumber: 55, description: "Adh-Dhariyat 31 - Al-Qamar 55" },
  { number: 54, juzNumber: 27, nameArabic: "الحزب ٥٤", nameEnglish: "Hizb 54", startSurahNumber: 55, startSurahName: "Ar-Rahman", startAyahNumber: 1, endSurahNumber: 57, endSurahName: "Al-Hadid", endAyahNumber: 29, description: "Ar-Rahman 1 - Al-Hadid 29" },
  { number: 55, juzNumber: 28, nameArabic: "الحزب ٥٥", nameEnglish: "Hizb 55", startSurahNumber: 58, startSurahName: "Al-Mujadilah", startAyahNumber: 1, endSurahNumber: 61, endSurahName: "As-Saff", endAyahNumber: 14, description: "Al-Mujadilah 1 - As-Saff 14" },
  { number: 56, juzNumber: 28, nameArabic: "الحزب ٥٦", nameEnglish: "Hizb 56", startSurahNumber: 62, startSurahName: "Al-Jumu'ah", startAyahNumber: 1, endSurahNumber: 66, endSurahName: "At-Tahrim", endAyahNumber: 12, description: "Al-Jumu'ah 1 - At-Tahrim 12" },
  { number: 57, juzNumber: 29, nameArabic: "الحزب ٥٧", nameEnglish: "Hizb 57", startSurahNumber: 67, startSurahName: "Al-Mulk", startAyahNumber: 1, endSurahNumber: 71, endSurahName: "Nuh", endAyahNumber: 28, description: "Al-Mulk 1 - Nuh 28" },
  { number: 58, juzNumber: 29, nameArabic: "الحزب ٥٨", nameEnglish: "Hizb 58", startSurahNumber: 72, startSurahName: "Al-Jinn", startAyahNumber: 1, endSurahNumber: 77, endSurahName: "Al-Mursalat", endAyahNumber: 50, description: "Al-Jinn 1 - Al-Mursalat 50" },
  { number: 59, juzNumber: 30, nameArabic: "الحزب ٥٩", nameEnglish: "Hizb 59", startSurahNumber: 78, startSurahName: "An-Naba", startAyahNumber: 1, endSurahNumber: 86, endSurahName: "At-Tariq", endAyahNumber: 17, description: "An-Naba 1 - At-Tariq 17" },
  { number: 60, juzNumber: 30, nameArabic: "الحزب ٦٠", nameEnglish: "Hizb 60", startSurahNumber: 87, startSurahName: "Al-A'la", startAyahNumber: 1, endSurahNumber: 114, endSurahName: "An-Nas", endAyahNumber: 6, description: "Al-A'la 1 - An-Nas 6" }
];
